# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Keystone < Formula
  desc "Project harness for coding agents — scaffolds harness/ and per-agent activation files into your repo."
  homepage "https://github.com/tacoda/keystone"
  version "0.9.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tacoda/keystone/releases/download/v0.9.2/keystone_0.9.2_darwin_x86_64.tar.gz"
      sha256 "012fc4c54cd7a7b8546a951d935021234d1fac5b07fae96f2cdf7aaaff9cf63f"

      define_method(:install) do
        bin.install "keystone"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tacoda/keystone/releases/download/v0.9.2/keystone_0.9.2_darwin_arm64.tar.gz"
      sha256 "6dade929d790a305ebb11f88332a85a0cccce15c97fe36ad04b50fbe7feb671d"

      define_method(:install) do
        bin.install "keystone"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tacoda/keystone/releases/download/v0.9.2/keystone_0.9.2_linux_x86_64.tar.gz"
      sha256 "00a3b1bdf0e86be06089d62534dc1171e6bf368d807faa1355098f45b8bf281b"
      define_method(:install) do
        bin.install "keystone"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tacoda/keystone/releases/download/v0.9.2/keystone_0.9.2_linux_arm64.tar.gz"
      sha256 "9c63961bd5302041adea2ee2ab2bd4b5c293059a5e8bf90237bd22965c6826f7"
      define_method(:install) do
        bin.install "keystone"
      end
    end
  end

  test do
    system "#{bin}/keystone", "version"
  end
end
